package options

// Section names, in display order.
const (
	SecModel         = "Model and thinking"
	SecDisplay       = "Display"
	SecInput         = "Input and editing"
	SecContext       = "Context and memory"
	SecPermissions   = "Permissions and safety"
	SecNotifications = "Notifications"
	SecIntegrations  = "Integrations"
)

// Table lists every user-facing setting mantle's /config offers. Keys and row IDs are
// Claude Code's API and used verbatim; labels and descriptions are mantle's own.
var Table = []Option{
	// ---- Model and thinking ----
	{Key: "model", Row: "model", Section: SecModel, Label: "Model",
		Description: "Model used for new sessions. Opens the model picker.",
		Type:        Text, Default: "default", Store: StoreUser, Write: WritePanel, Panel: "model"},
	{Key: "effortLevel", Section: SecModel, Label: "Effort",
		Description: "How much reasoning the model spends per turn. Opens the effort slider.",
		Type:        Enum, Values: []string{"low", "medium", "high", "xhigh"}, Default: "high",
		Store: StoreUser, Write: WritePanel, Panel: "effort", SessionOK: true},
	{Key: "alwaysThinkingEnabled", Row: "thinking", Section: SecModel, Label: "Extended thinking",
		Description: "Let the model think before answering. Some models cannot turn it off.",
		Type:        Bool, Default: true, UnsetWhen: true, Store: StoreUser, Write: WriteConfigWriter, SessionOK: true},
	{Key: "fastMode", Row: "fast", Section: SecModel, Label: "Fast mode",
		Description: "Faster output on models that offer it, at a higher price. Opens /fast.",
		Type:        Bool, Default: false, Store: StoreUser, Write: WritePanel, Panel: "fast"},
	{Key: "outputStyle", Row: "outputStyle", Section: SecModel, Label: "Output style",
		Description: "How responses are written: default, explanatory, learning, … Opens the style picker.",
		Type:        Text, Default: "default", Store: StoreLocal, Write: WritePanel, Panel: "outputStyle"},
	{Key: "language", Row: "language", Section: SecModel, Label: "Response language",
		Description: "Language Claude replies in. Use a name or ISO code; \"default\" means English.",
		Type:        Text, Default: "", UnsetWhen: "", Store: StoreUser, Write: WriteConfigWriter},

	// ---- Display ----
	{Key: "theme", Row: "theme", Section: SecDisplay, Label: "Theme",
		Description: "Colour theme. Opens the theme picker with a live preview.",
		Type:        Enum, Values: []string{"auto", "dark", "light", "dark-daltonized", "light-daltonized", "dark-ansi", "light-ansi"},
		Default: "dark", Store: StoreUser, Write: WritePanel, Panel: "theme", GlobalFallback: true},
	{Key: "verbose", Row: "verbose", Section: SecDisplay, Label: "Verbose output",
		Description: "Show full tool output and details instead of compact summaries.",
		Type:        Bool, Default: false, Store: StoreUser, Write: WriteConfigWriter, GlobalFallback: true},
	{Key: "showTurnDuration", Row: "turnDuration", Section: SecDisplay, Label: "Turn duration",
		Description: "Print how long each turn took when it finishes.",
		Type:        Bool, Default: true, Store: StoreUser, Write: WriteConfigWriter, GlobalFallback: true},
	{Key: "showMessageTimestamps", Row: "timestamps", Section: SecDisplay, Label: "Message timestamps",
		Description: "Show the time next to each message.",
		Type:        Bool, Default: false, Store: StoreUser, Write: WriteConfigWriter, GlobalFallback: true},
	{Key: "timeFormat", Row: "timeFormat", Section: SecDisplay, Label: "Time format",
		Description: "Clock style for timestamps.",
		Type:        Enum, Values: []string{"auto", "12-hour", "24-hour", "24-hour-utc"}, Default: "auto",
		Store: StoreUser, Write: WriteConfigWriter},
	{Key: "spinnerTipsEnabled", Row: "tips", Section: SecDisplay, Label: "Tips while working",
		Description: "Show a tip under the spinner while Claude works.",
		Type:        Bool, Default: true, Store: StoreLocal, Write: WriteConfigWriter},
	{Key: "prefersReducedMotion", Row: "reduceMotion", Section: SecDisplay, Label: "Reduce motion",
		Description: "Calm the spinner and other animations.",
		Type:        Bool, Default: false, Store: StoreLocal, Write: WriteConfigWriter},
	{Key: "terminalProgressBarEnabled", Row: "progressBar", Section: SecDisplay, Label: "Terminal progress bar",
		Description: "Show progress in the terminal tab or dock icon where the terminal supports it.",
		Type:        Bool, Default: true, Store: StoreUser, Write: WriteConfigWriter, GlobalFallback: true},
	{Key: "todoFeatureEnabled", Section: SecDisplay, Label: "Task list",
		Description: "Show Claude's task checklist above the prompt.",
		Type:        Bool, Default: true, Store: StoreUser, Write: WriteConfigWriter, GlobalFallback: true},
	{Key: "syntaxHighlightingDisabled", Section: SecDisplay, Label: "Disable syntax highlighting",
		Description: "Render code blocks and diffs without colour highlighting.",
		Type:        Bool, Default: false, Store: StoreUser, Write: WriteConfigWriter},
	{Key: "showThinkingSummaries", Section: SecDisplay, Label: "Thinking summaries",
		Description: "Show a short summary of the model's thinking in the transcript.",
		Type:        Bool, Default: false, Store: StoreUser, Write: WriteConfigWriter},
	{Key: "defaultView", Row: "defaultView", Section: SecDisplay, Label: "Default view",
		Description: "Which view a session opens in: chat only, or the full transcript.",
		Type:        Enum, Values: []string{"default", "chat", "transcript"}, Default: "default", UnsetWhen: "default",
		Store: StoreLocal, Write: WriteConfigWriter},
	{Key: "tui", Section: SecDisplay, Label: "Renderer",
		Description: "Inline output in the terminal's scrollback, or a fullscreen view.",
		Type:        Enum, Values: []string{"default", "fullscreen"}, Default: "default", Store: StoreUser, Write: WriteConfigWriter},
	{Key: "autoScrollEnabled", Row: "autoScroll", Section: SecDisplay, Label: "Follow output",
		Description: "In fullscreen, keep scrolling to the newest output.",
		Type:        Bool, Default: true, Store: StoreUser, Write: WriteConfigWriter, GlobalFallback: true, When: FullscreenOnly},
	{Key: "terminalTitleFromRename", Section: SecDisplay, Label: "Title from session name",
		Description: "Use the session's name as the terminal window title.",
		Type:        Bool, Default: true, Store: StoreUser, Write: WriteConfigWriter},

	// ---- Input and editing ----
	{Key: "editorMode", Row: "editor", Section: SecInput, Label: "Editor mode",
		Description: "Key bindings for the prompt: standard readline-style keys or vim.",
		Type:        Enum, Values: []string{"normal", "vim"}, Default: "normal",
		Store: StoreUser, Write: WriteConfigWriter, GlobalFallback: true},
	{Key: "promptSuggestionEnabled", Row: "promptSuggestionEnabled", Section: SecInput, Label: "Prompt suggestions",
		Description: "Offer a likely next prompt as grey text you can accept.",
		Type:        Bool, Default: true, Store: StoreUser, Write: WriteConfigWriter},
	{Key: "emojiCompletionEnabled", Section: SecInput, Label: "Emoji completion",
		Description: "Complete :shortcodes: to emoji while typing.",
		Type:        Bool, Default: true, Store: StoreUser, Write: WriteConfigWriter},
	{Key: "respondToBashCommands", Section: SecInput, Label: "Reply to ! commands",
		Description: "After a ! shell command, let Claude comment on its output.",
		Type:        Bool, Default: false, Store: StoreUser, Write: WriteConfigWriter},
	{Key: "respectGitignore", Row: "gitignore", Section: SecInput, Label: "Respect .gitignore in @ search",
		Description: "Leave ignored files out of @ file suggestions.",
		Type:        Bool, Default: true, Store: StoreGlobal, Write: WriteEngineConfig},
	{Key: "copyFullResponse", Row: "copyFullResponse", Section: SecInput, Label: "/copy copies the whole reply",
		Description: "Skip the picker in /copy and copy the full last response.",
		Type:        Bool, Default: false, Store: StoreGlobal, Write: WriteEngineConfig},
	{Key: "copyOnSelect", Row: "copyOnSelect", Section: SecInput, Label: "Copy on select",
		Description: "In fullscreen, copy text to the clipboard as soon as it is selected.",
		Type:        Bool, Default: true, Store: StoreGlobal, Write: WriteEngineConfig, When: FullscreenOnly},
	{Key: "externalEditorContext", Row: "externalEditorContext", Section: SecInput, Label: "Last reply in external editor",
		Description: "When opening the prompt in $EDITOR, include Claude's last reply for reference.",
		Type:        Bool, Default: false, Store: StoreGlobal, Write: WriteEngineConfig},

	// ---- Context and memory ----
	{Key: "autoCompactEnabled", Row: "autoCompact", Section: SecContext, Label: "Auto-compact",
		Description: "Summarise the conversation automatically when the context fills up.",
		Type:        Bool, Default: true, Store: StoreUser, Write: WriteConfigWriter, GlobalFallback: true},
	{Key: "precomputeCompactionEnabled", Row: "precomputeCompactionEnabled", Section: SecContext, Label: "Prepare compaction early",
		Description: "Build the summary in the background before it is needed, so compaction is instant.",
		Type:        Bool, Default: true, Store: StoreUser, Write: WriteConfigWriter},
	{Key: "fileCheckpointingEnabled", Row: "checkpoints", Section: SecContext, Label: "Code checkpoints",
		Description: "Keep file snapshots so /rewind can restore code.",
		Type:        Bool, Default: true, Store: StoreUser, Write: WriteConfigWriter, GlobalFallback: true},
	{Key: "awaySummaryEnabled", Row: "recap", Section: SecContext, Label: "Recap after a break",
		Description: "Show a one-line recap when you come back to an idle session.",
		Type:        Bool, Default: true, Store: StoreUser, Write: WriteConfigWriter},
	{Key: "autoMemoryEnabled", Section: SecContext, Label: "Auto memory",
		Description: "Let Claude save and recall notes about you and the project between sessions.",
		Type:        Bool, Default: true, Store: StoreUser, Write: WriteConfigWriter},
	{Key: "autoContinueAtUsageLimit", Row: "autoContinueAtUsageLimit", Section: SecContext, Label: "Continue after usage limit",
		Description: "Wait for a usage limit to reset and carry on automatically.",
		Type:        Bool, Default: true, Store: StoreUser, Write: WriteConfigWriter},

	// ---- Permissions and safety ----
	{Key: "permissions.defaultMode", Row: "permissionMode", Section: SecPermissions, Label: "Default permission mode",
		Description: "Permission mode new sessions start in.",
		Type:        Enum, Values: []string{"default", "plan", "acceptEdits", "auto", "dontAsk"}, Default: "default",
		Store: StoreUser, Write: WriteConfigWriter},
	{Key: "useAutoModeDuringPlan", Row: "useAutoModeDuringPlan", Section: SecPermissions, Label: "Auto mode while planning",
		Description: "Let the auto-mode classifier approve read-only actions in plan mode.",
		Type:        Bool, Default: true, Store: StoreUser, Write: WriteConfigWriter},
	{Key: "askUserQuestionTimeout", Row: "askUserQuestionTimeout", Section: SecPermissions, Label: "Question timeout",
		Description: "How long Claude waits for an answer to a multiple-choice question before going on.",
		Type:        Enum, Values: []string{"never", "60s", "5m", "10m"}, Default: "never", Store: StoreUser, Write: WriteConfigWriter},
	{Key: "dialogExpiry", Row: "dialogExpiry", Section: SecPermissions, Label: "Dialog expiry",
		Description: "How long an unanswered prompt stays open before it is dismissed.",
		Type:        Enum, Values: []string{"default", "60s", "5m", "10m", "never"}, Default: "default", UnsetWhen: "default",
		Store: StoreUser, Write: WriteConfigWriter},
	{Key: "worktree.baseRef", Row: "worktreeBaseRef", Section: SecPermissions, Label: "Worktree base",
		Description: "Where new worktrees branch from: the latest remote default branch, or your current HEAD.",
		Type:        Enum, Values: []string{"fresh", "head"}, Default: "fresh", Store: StoreUser, Write: WriteConfigWriter},

	// ---- Notifications ----
	{Key: "preferredNotifChannel", Row: "notifChannel", Section: SecNotifications, Label: "Notifications",
		Description: "How mantle gets your attention when Claude needs input or finishes.",
		Type:        Enum, Values: []string{"auto", "iterm2", "terminal_bell", "iterm2_with_bell", "kitty", "ghostty", "notifications_disabled"},
		Default: "auto", Store: StoreUser, Write: WriteConfigWriter, GlobalFallback: true},
	{Key: "inputNeededNotifEnabled", Row: "inputNeededNotifEnabled", Section: SecNotifications, Label: "Push when input is needed",
		Description: "Send a push notification to your phone when Claude is waiting on you.",
		Type:        Bool, Default: false, Store: StoreUser, Write: WriteConfigWriter, GlobalFallback: true},
	{Key: "agentPushNotifEnabled", Row: "agentPushNotifEnabled", Section: SecNotifications, Label: "Push when agents finish",
		Description: "Send a push notification when a background agent completes.",
		Type:        Bool, Default: false, Store: StoreUser, Write: WriteConfigWriter, GlobalFallback: true},

	// ---- Integrations ----
	{Key: "prStatusFooterEnabled", Row: "prStatus", Section: SecIntegrations, Label: "Pull request status",
		Description: "Show the current branch's pull request and its checks in the footer.",
		Type:        Bool, Default: true, Store: StoreGlobal, Write: WriteEngineConfig},
	{Key: "autoConnectIde", Row: "autoConnectIde", Section: SecIntegrations, Label: "Connect to IDE automatically",
		Description: "Connect to a running IDE at startup when exactly one is found.",
		Type:        Bool, Default: false, Store: StoreGlobal, Write: WriteEngineConfig, When: NotInIDE},
	{Key: "autoInstallIdeExtension", Row: "autoInstallIdeExtension", Section: SecIntegrations, Label: "Install IDE extension",
		Description: "Install the Claude Code extension when running inside an IDE terminal.",
		Type:        Bool, Default: true, Store: StoreGlobal, Write: WriteEngineConfig},
	{Key: "diffTool", Row: "diffTool", Section: SecIntegrations, Label: "Diff viewer",
		Description: "Review proposed edits in the terminal, or in the connected IDE when there is one.",
		Type:        Enum, Values: []string{"auto", "terminal"}, Default: "auto", Store: StoreGlobal, Write: WriteEngineConfig, When: IDEConnected},
	{Key: "claudeInChromeDefaultEnabled", Row: "chrome", Section: SecIntegrations, Label: "Chrome integration by default",
		Description: "Enable browser automation through Claude in Chrome for new sessions.",
		Type:        Bool, Default: false, Store: StoreGlobal, Write: WriteEngineConfig},
	{Key: "teammateMode", Row: "teammateMode", Section: SecIntegrations, Label: "Teammate panes",
		Description: "Where agent teammates run: split panes in tmux or iTerm2, or inside this session.",
		Type:        Enum, Values: []string{"auto", "tmux", "iterm2", "in-process"}, Default: "in-process",
		Store: StoreUser, Write: WriteConfigWriter, GlobalFallback: true},
}
