package main

import (
	"fmt"
	"io"
	"strings"
)

// writeMarkdown renders docs/parity-drift.md.
func writeMarkdown(w io.Writer, r Report) error {
	var b strings.Builder
	b.WriteString("# Parity drift\n\n")
	fmt.Fprintf(&b, "Generated by `go run ./scripts/drift` (`make drift`) on %s against claude %s; baseline %s. Do not edit by hand.\n\n",
		r.Generated, orDash(r.ClaudeVersion), orDash(r.BaselineVersion))
	if r.Failed() {
		b.WriteString("**Result: drift found.** Unclassified or mismatched items need a decision in mantle's tables.\n\n")
	} else {
		b.WriteString("**Result: no unclassified items.**\n\n")
	}

	b.WriteString("| List | Source | Items | Unclassified | Mismatch | Removed | New | Gone |\n")
	b.WriteString("|---|---|---:|---:|---:|---:|---:|---:|\n")
	for _, s := range r.Summary {
		if s.Error != "" {
			fmt.Fprintf(&b, "| %s | %s | unavailable | | | | | |\n", s.Kind, s.Source)
			continue
		}
		fmt.Fprintf(&b, "| %s | %s | %d | %d | %d | %d | %d | %d |\n",
			s.Kind, s.Source, s.Items, s.Unclassified, s.Mismatch, s.Removed, s.New, s.Gone)
	}

	sections := []struct{ status, title, blurb string }{
		{StatusUnclassified, "Unclassified (fails `make drift`)", "claude has these and mantle doesn't say how it handles them."},
		{StatusMismatch, "Mismatched (fails `make drift`)", "Both know these, but disagree."},
		{StatusRemoved, "Removed from claude", "mantle's tables still list these; claude no longer has them."},
		{StatusNew, "New since the baseline", "Handled without mantle changes (passthrough). Accept the baseline once reviewed."},
		{StatusGone, "Gone since the baseline", "Informational."},
	}
	for _, sec := range sections {
		var rows []Finding
		for _, f := range r.Findings {
			if f.Status == sec.status {
				rows = append(rows, f)
			}
		}
		if len(rows) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\n## %s\n\n%s\n\n| List | Item | Detail |\n|---|---|---|\n", sec.title, sec.blurb)
		for _, f := range rows {
			name := "`" + f.Name + "`"
			if f.Scope != "" {
				name = "`" + f.Scope + "` " + name
			}
			fmt.Fprintf(&b, "| %s | %s | %s |\n", f.Kind, name, f.Detail)
		}
	}

	var unavailable []Summary
	for _, s := range r.Summary {
		if s.Error != "" {
			unavailable = append(unavailable, s)
		}
	}
	if len(unavailable) > 0 {
		b.WriteString("\n## Not collected\n\n| List | Reason |\n|---|---|\n")
		for _, s := range unavailable {
			fmt.Fprintf(&b, "| %s | %s |\n", s.Kind, s.Error)
		}
	}
	_, err := io.WriteString(w, b.String())
	return err
}

func orDash(s string) string {
	if s == "" {
		return "-"
	}
	return s
}
